final_rle:
	.db $c, $3e
	;;;; Debut data
	.db 1,$47
	.db 61,$49
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$46
	.db 1,$47
	.db 60,$0
	.db 1,$83
	.db 1,$47
	.db 60,$0
	.db 1,$83
	.db 62,$45
	.db 0 ; marqueur de fin
