;########################################################
;# [megaText.inc]
;#-------------------------------------------------------
;# ROUTINES CONTENUES:
;# AUCUNE ! 
;#-------------------------------------------------------
;# DONNEES CONTENUES :
;#-------------------------------------------------------
;#  On trouvera ici les textes d'intro et outro 
;#  et peut-être plus si nous rajoutons des animations
;#  We put here the intro and outro text data 
;#-------------------------------------------------------

; Beat dr wily or we will die 



intro_text:
.db "The year is 2042.", 0,0
.db "Megaman has laid waste", 0 
.db "to countless robots sent", 0
.db "by Dr. Wily.", 0,0
.db "Time and time again Rock", 0
.db "has proven himself and", 0 
.db "brought the world back", 0
.db "from the brink of", 0
.db "destruction.",0,0
.db "Dr. Light has long since",0
.db "passed.", 0,0
.db "The world has found peace", 0
.db "and Dr. Wily has gone silent.",0,0
.db "Perhaps, just perhaps,",0
.db "that last battle was the", 0
.db "straw that broke the once", 0
.db "vengeful doctor's back.",0,0
.db "However, just as all seemed",0
.db "well and our hero was",0
.db "taking a well-deserved",0
.db "break, strange occurrences", 0 
.db "-- sightings of foes defeated", 0
.db "long ago -- began popping", 0
.db "up around the globe", 0,0
.db "Will Rock don his iconic", 0
.db "helmet and Mega Blaster to", 0
.db "save the world once again?", 0,0,0,0,0,0,0,0,0,0,0,$FF	;les extras zéros sont pour ne pas quitter
  															;jusqu'à finir de scroller le dernier texte  
final_text:
.db "You know, I've been",0
.db "waiting for you.",0,0
.db "I knew you would come.",0,0
.db "Since my last defeat, I've",0
.db "spent a lot of time thinking.",0,0
.db "Alone and waiting for the",0
.db "one true creation i could",0
.db "really be proud of to",0
.db "return, I began to repair",0
.db "some of my most faithful",0
.db "robots.",0,0
.db "As one by one their gears",0
.db "began to click once again,",0
.db "I realized that sometimes",0
.db "an invention outgrows its",0
.db "master, sometimes a son...",0
.db "outgrows his own father.",0,0
.db "I realized that as long as",0
.db "this creation existed, my",0
.db "work could never continue.",0
.db "I also realized, however,",0
.db "that without this creation,",0
.db "my inspiration,",0
.db "my motivation,",0
.db "everything i work and aspire",0
.db "to would have no meaning.",0,0
.db "That's why today, there is",0
.db "no turning back.",0,0
.db "Today, it isn't you or me,",0
.db "it isn't life or death, there",0
.db "can only be death,",0
.db "destruction.",0,0
.db "Haha!",0,0
.db "Today it's over.",0
.db "Everything ends.",0,0
.db "This damned city will burn,",0
.db "crumble, crash after all",0
.db "these years burdened by my",0
.db "undying love and hatred",0
.db "for it.",0,0
.db "This time, there's no way",0
.db "out. There is no key,",0
.db "no magic, no illusion,",0
.db "no secret.",0,0
.db "This is it, all there is.",0,0
.db "And in just (X) minutes,",0
.db "there won't even be this.",0,0
.db "Ha, yes!",0,0
.db "In just (X) minutes, I will",0
.db "finally have the satisfaction",0
.db "of destroying that which",0
.db "destroyed me.",0,0
.db "Oh, my boy...",0
.db "how you have grown...!",0,0,0,0,0,0,0,0,0,0,0,$FF

wily_text:
.db "My son...",0,0
.db "I just don't",0
.db "understand. I don't",0
.db "understand why you protect",0
.db "this world of hatred,",0
.db "exploitation, destruction.",0
.db "Where is its beauty?",0,0
.db "This human world is nothing",0
.db "more than a bunch of",0
.db "cockroaches trampling",0
.db "over top each other,",0
.db "spreading their filth to",0
.db "everything they touch.",0,0
.db "There is no love, no passion,",0
.db "everything is driven by",0
.db "greed.",0,0
.db "Millions working, not for",0
.db "themselves but for someone",0
.db "else. Ignoring their dreams",0
.db "in the name of greed,",0
.db "in the name of more.",0,0
.db "They sicken me!",0,0
.db "Maybe my thoughts disgust",0
.db "you, horrify you, but what",0
.db "you represent disgusts and",0
.db "horrifies me!",0,0
.db "My son...",0,0
.db "I admire you, your courage,",0
.db "your sacrifice. This world",0
.db "really doesn't deserve you.",0
.db "Maybe some day you will",0
.db "understand me, and why",0
.db "I did what I did...",0,0,0,0,0,0,0,0,0
.db "Copy, Modify,",0
.db "Distribute, Enjoy",0,0
.db "Death to copyright!",0,0
.db "Made with love, 2012-2013",0,0,0,$FF
