;########################################################
;# [megaTitlePicture.inc]
;#-------------------------------------------------------
;# ROUTINES CONTENUES:
;# AUCUNE !
;#-------------------------------------------------------
;# On trouve ici le titre quand on démarre le jeu
;# Simply the title when you start the game
;#-------------------------------------------------------

; I need more power

title_picture:
#include "zsprites/megaLogo.bmp"
title_picture_end:
